# name: CI/CD with Database

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     name: Build, Test, and Deploy
#     runs-on: ubuntu-latest

#     services:
#       mysql:
#         image: mysql:8.0
#         env:
#           MYSQL_ROOT_PASSWORD: root
#           MYSQL_DATABASE: mydb
#           MYSQL_USER: user
#           MYSQL_PASSWORD: password
#         ports:
#           - 3306:3306
#         options: >-
#           --health-cmd="mysqladmin ping -h localhost"
#           --health-interval=10s
#           --health-timeout=5s
#           --health-retries=3

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'temurin'
#           java-version: '17'
#           cache: 'maven'

#       - name: Wait for MySQL to be Ready
#         run: |
#           echo "Waiting for MySQL..."
#           sleep 15

#       - name: Run Database Migrations (if needed)
#         run: |
#           mysql -h 127.0.0.1 -u user -ppassword mydb < src/main/resources/schema.sql

#       - name: Build with Maven
#         run: mvn clean package -DskipTests

#       - name: Run Tests
#         env:
#           SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/mydb
#           SPRING_DATASOURCE_USERNAME: user
#           SPRING_DATASOURCE_PASSWORD: password
#         run: mvn test

#       - name: Set Version Tag
#         run: |
#           VERSION="v${{ github.run_number }}"
#           echo "DOCKER_TAG=$VERSION" >> $GITHUB_ENV

#       - name: Build & Push Docker Image
#         uses: mr-smithers-excellent/docker-build-push@v5
#         with:
#           image: amarpal/to-do-app-springboot
#           tags: latest,${{ env.DOCKER_TAG }}
#           registry: docker.io
#           dockerfile: Dockerfile
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
